hdhomerun_host = "192.168.1.115"
ffmpeg_path = "D:/wallop/ffmpeg_x86_64/ffmpeg.exe"
transcoding_path = "./tmp"
port = "8888"
hd_start = 1000

[channel_logos]
1009 = "cbs.png"
1007 = "abc.png"
1005 = "fox.png"
1004 = "nbc.png"
